### PR TITLE
LPS-73738 Javadoc Review

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4123, please review my edits to make sure I didn't distort anything. cc @inacionery, @codyhoag

### CODE REVIEW

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hi @rbohl :) The commit is good but the commit's message is not very clear. We try to make as clear as we can( i.e Edition of the javadoc related do the unpublish configuration icon's action , or something).

Can you take a look at this, plz?

**Comment by rbohl** [comment]
@jeyvison , I amended the commit message. Let me know if it's better now.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
That looks awesome! Thanks @rbohl

**Comment by jeyvison** [comment]
Pull request forwarded to https://github.com/liferay/com-liferay-portal-workflow/pull/331. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
